name: CI with Dependency Caching

on:
  push:
    branches:
      - main # IMPORTANT: Change to 'master' if that's your default branch
#jdv
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache npm dependencies
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ~/.npm 
        key: cache-ecb5904

    - name: Echo cache hit/miss result
      id: prime-cache-ecb5904
      run: |
        if [[ "${{ steps.cache-npm.outputs.cache-hit }}" == "true" ]]; then
          echo "Cache hit for key: ${{ steps.cache-npm.outputs.cache-primary-key }}"
        else
          echo "Cache miss. A new cache will be created."
        fi

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: echo "Build step would run here..."
